importing pandas, numpy, matplotlib, seaborn and waring library

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\ml-projectguide2\notebook\data\stud.csv')

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.shape

(1000, 8)

3 datachecks to perform
check missing values
check data type
check number of unique values of each column
check statistics of data
check various categories present in different categorical columns

In [5]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

there are no missing values in this data set

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race_ethnicity               1000 non-null   str
 2   parental_level_of_education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test_preparation_course      1000 non-null   str
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [8]:
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [9]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [10]:
print("categories in 'gender' variable  :", end =" " )
print(df['gender'].unique())

print("categories in 'race_ethnicity' variable  :", end =" " )
print(df['race_ethnicity'].unique())

print("categories in 'parental_level_of_education' variable  :", end =" " )
print(df['parental_level_of_education'].unique())

print("categories in 'lunch' variable  :", end =" " )
print(df['lunch'].unique())

print("categories in 'test_preparation_course' variable  :", end =" " )
print(df['test_preparation_course'].unique())

categories in 'gender' variable  : <StringArray>
['female', 'male']
Length: 2, dtype: str
categories in 'race_ethnicity' variable  : <StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str
categories in 'parental_level_of_education' variable  : <StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str
categories in 'lunch' variable  : <StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str
categories in 'test_preparation_course' variable  : <StringArray>
['none', 'completed']
Length: 2, dtype: str

In [11]:
# define numerical and categorical features
numeric_features = [feature for feature in df.columns if df[feature].dtype == int]
categorical_features = [feature for feature in df.columns if df[feature].dtype != int]

# print columns
print('we have {} numerical features'.format(len(numeric_features), numeric_features))
print('we have {} categorical features'.format(len(categorical_features), categorical_features))

we have 3 numerical features
we have 5 categorical features

In [12]:
categorical_features

['gender',
 'race_ethnicity',
 'parental_level_of_education',
 'lunch',
 'test_preparation_course']

In [13]:
numeric_features

['math_score', 'reading_score', 'writing_score']

In [14]:
df['total_score'] = df['math_score'] + df['reading_score'] + df['writing_score']
df['average_score'] = df['total_score']/3
df.head(3)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667

In [16]:
reading_full = df[df['reading_score'] == 100]['average_score'].count()
writing_full = df[df['writing_score'] == 100]['average_score'].count()
math_full = df[df['math_score'] == 100]['average_score'].count()

print (f'number of students with full marks in math: {math_full}')
print (f'number of students with full marks in reading: {reading_full}')
print (f'number of students with full marks in writing: {writing_full}')

number of students with full marks in math: 7
number of students with full marks in reading: 17
number of students with full marks in writing: 14

In [17]:
reading_less_20 = df[df['reading_score'] <=20]['average_score'].count()
writing_less_20 = df[df['writing_score'] <=20]['average_score'].count()
math_less_20 = df[df['math_score'] <=20]['average_score'].count()

print (f'number of students with full marks in math: {math_less_20}')
print (f'number of students with full marks in reading: {reading_less_20}')
print (f'number of students with full marks in writing: {writing_less_20}')

number of students with full marks in math: 4
number of students with full marks in reading: 1
number of students with full marks in writing: 3